#ARG CLI_IMAGE
#FROM ${CLI_IMAGE} as cli
FROM php/7.3.4-fpm-stretch
#FROM amazeeio/php:7.2-fpm
#FROM amazeeio/php:7.2-cli-drupal

# We don't need the composer.lock file
# COPY composer.json composer.lock /app/
#COPY scripts /app/scripts

# Installing composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY blog2 /app
COPY composer.json /app
COPY scripts /app/scripts
#RUN ln -s /app /application
RUN rm -f /app/composer.lock
RUN type composer
RUN ls -al /app
RUN rm -rf /app/vendor
RUN composer install --dev

# Define where the Drupal Root is located
ENV WEBROOT=web
